# Generated by Django 6.0.2 on 2026-03-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер стола')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('reserved', 'Забронирован')], default='free', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
    ]
