# Generated by Django 6.0.2 on 2026-03-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
    ]
