# Generated by Django 6.0.2 on 2026-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR-код')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
